services:
  db:
    image: mariadb
    container_name: mariadb_springboot_essentials
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
    - "3306:3306"
    volumes:
    - devdojo_data:/var/lib/mysql

volumes:
  devdojo_data: