server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/springboot_essentials_anime?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MariaDBDialect

logging:
  level:
    org:
      hibernate:
        SQL: debug

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info, health, metrics, prometheus
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: springboot-essentials

info:
  app:
    name: Spring Boot Essentials
    description: Repository that contains practical knowledge about various Spring Framework projects.