server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/springboot_essentials_anime?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MariaDBDialect

logging:
  level:
    org:
      hibernate:
        SQL: debug